"""GitHub PR comment formatter.

Bridges `prusik scan` / `prusik verify-loop` / `prusik findings` output to the
markdown shape GitHub renders nicely in PR comments. The composite
action at `action.yml` pipes findings JSON through this formatter
(via `prusik ci-comment`) and posts the result with `gh pr comment`.

Contract (stable as part of the v0.26 schema_version 1.0 promise):
  - Input: JSON from `prusik scan --json` OR `prusik verify-loop check --json`
    OR `prusik findings --json`. Auto-detected by top-level shape.
  - Output: GitHub-flavored markdown to stdout.

Mission boundary preserved — the comment is decision-support for the
reviewer, not a gate. The Action can opt-in to fail-on-findings, but
the default behavior is "emit signal, let humans decide."

Honest scope:
  - The formatter is conservative on length — collapses long output
    into `<details>` blocks so PRs with many findings don't drown the
    review thread.
  - Suggested-test scaffolds are formatted as code blocks (paste-ready)
    with stack-appropriate language tags for syntax highlighting.
"""

from __future__ import annotations

import json
import sys


# Maximum findings shown inline before collapsing to <details>
_INLINE_LIMIT = 5


def _format_scan(data: dict) -> str:
    """Format `prusik scan --json` output as PR comment markdown."""
    out: list[str] = []
    total = data.get("total", 0)
    stats = data.get("stats", {})
    root = data.get("root", "?")

    if total == 0:
        out.append("## ✅ prusik scan — clean")
        out.append("")
        out.append(f"Scanned **{stats.get('total_files', '?')}** file(s); "
                   f"no binding-mismatch or test-reach flags raised.")
        if stats.get("truncated"):
            out.append("")
            out.append(f"> ⚠ scan truncated at --limit "
                       f"{stats.get('file_limit', '?')}; "
                       f"raise the limit or narrow scope to scan more.")
        return "\n".join(out)

    out.append(f"## ⚠ prusik scan — {total} flag(s)")
    out.append("")
    out.append(f"Scanned **{stats.get('total_files', '?')}** file(s) "
               f"under `{root}`. Findings are **decision-support, not "
               f"gating** — adjudicate each flag before acting.")
    out.append("")

    # The canonical `findings` list (normalized Finding.to_json) is the only
    # representation — group it by detector + class.
    findings = data.get("findings", [])
    fetch_url = [f for f in findings
                 if f.get("detector") == "binding" and f.get("class") == "fetch_url"]
    form_name = [f for f in findings
                 if f.get("detector") == "binding" and f.get("class") == "form_name"]

    if fetch_url:
        out.append(f"### fetch-URL ↔ route-path mismatches ({len(fetch_url)})")
        out.append("")
        out.extend(_format_findings_block(fetch_url))

    if form_name:
        out.append(f"### form-name ↔ handler-key dropthroughs "
                   f"({len(form_name)})")
        out.append("")
        out.extend(_format_findings_block(form_name))

    reach = [f for f in findings if f.get("detector") == "test-reach"]
    if reach:
        out.append(f"### test-reach cross-touch-set ({len(reach)})")
        out.append("")
        for f in reach[:_INLINE_LIMIT]:
            meta = f.get("meta", {})
            cid = meta.get("contract_id", "?")
            kind = meta.get("contract_kind", "?")
            refs = meta.get("references", [])[:3]
            out.append(f"- **{kind}**: `{cid}`")
            for r in refs:
                out.append(f"  - referenced by: `{r}`")
        out.append("")

    # Custom / pluggable detectors (anything beyond the two built-ins).
    custom: dict[str, list] = {}
    for f in findings:
        det = f.get("detector")
        if det in ("binding", "test-reach", None):
            continue
        custom.setdefault(det, []).append(f)
    for det in sorted(custom):
        fs = custom[det]
        out.append(f"### {det} ({len(fs)})")
        out.append("")
        for f in fs[:_INLINE_LIMIT]:
            loc = f.get("file") or ""
            if f.get("line"):
                loc = f"{loc}:{f['line']}"
            sev = f.get("severity", "?")
            head = f"`{loc}` " if loc else ""
            out.append(f"- **[{sev}]** {head}— {f.get('message', '')}")
        if len(fs) > _INLINE_LIMIT:
            out.append(f"- ... +{len(fs) - _INLINE_LIMIT} more")
        out.append("")

    out.append("---")
    out.append("*Generated by [`prusik scan`]("
               "https://github.com/getprusik/prusik) — "
               "see suggested-test scaffolds below each flag for "
               "paste-ready regression-blockers.*")
    return "\n".join(out)


def _format_findings_block(findings: list[dict]) -> list[str]:
    """Per-finding markdown: location, expected, suggested test scaffold."""
    out: list[str] = []
    inline = findings[:_INLINE_LIMIT]
    overflow = findings[_INLINE_LIMIT:]

    for f in inline:
        out.extend(_format_single_finding(f))

    if overflow:
        out.append("<details>")
        out.append(f"<summary>... and {len(overflow)} more flag(s) "
                   f"(click to expand)</summary>")
        out.append("")
        for f in overflow:
            out.extend(_format_single_finding(f))
        out.append("</details>")
        out.append("")

    return out


def _format_single_finding(f: dict) -> list[str]:
    """Render one normalized binding finding (canonical Finding.to_json shape)."""
    out: list[str] = []
    loc = f.get("file", "?")
    line = f.get("line")
    locstr = f"{loc}:{line}" if line else loc
    cls = f.get("class", "?")
    meta = f.get("meta", {})
    expected = f.get("expected", [])

    if cls == "fetch_url":
        out.append(f"- **`{locstr}`** — fetches `{meta.get('url', '?')}` ")
        if expected:
            out.append(f"  - suggested URL: `{expected[0]}`")
    elif cls == "form_name":
        out.append(f"- **`{locstr}`** — "
                   f"`<input name=\"{meta.get('name', '?')}\">`")
        if expected:
            out.append(f"  - handler keys touched: "
                       f"`{', '.join(expected[:5])}`")

    sug = f.get("suggested_test")
    if sug:
        stack = sug.get("stack", "python")
        lang = "python" if stack == "python" else "javascript"
        out.append("  - **suggested regression test** "
                   "(paste into your suite):")
        out.append("")
        out.append(f"  ```{lang}")
        for code_line in sug.get("code", "").splitlines():
            out.append(f"  {code_line}")
        out.append("  ```")
    out.append("")
    return out


def _format_verify_loop(data: dict) -> str:
    """Format `prusik verify-loop check --json` output as PR comment."""
    agg = data.get("aggregate", {})
    closed = agg.get("loop_closed", False)
    total = agg.get("t0_findings", 0)
    resolved = agg.get("resolved", 0)

    out: list[str] = []
    if total == 0:
        out.append("## ✅ prusik verify-loop — no T0 findings")
        out.append("")
        out.append("Nothing to verify (T0 was already clean).")
        return "\n".join(out)

    if closed:
        out.append(f"## ✅ prusik verify-loop — closed end-to-end "
                   f"({resolved}/{total})")
    else:
        out.append(f"## ⚠ prusik verify-loop — partial ({resolved}/{total})")

    out.append("")
    out.append(f"T0 recorded **{total}** finding(s); **{resolved}** "
               f"resolved at T1.")
    out.append("")

    statuses: dict[str, list] = {}
    for r in data.get("per_finding", []):
        statuses.setdefault(r.get("status", "?"), []).append(r)

    for status, items in sorted(statuses.items()):
        emoji = {
            "resolved": "✅",
            "fixed-but-no-test": "⚠",
            "test-added-but-fails": "❌",
            "still-present": "❌",
        }.get(status, "•")
        out.append(f"### {emoji} {status} ({len(items)})")
        out.append("")
        for r in items[:_INLINE_LIMIT]:
            out.append(f"- `{r.get('id', '?')}`")
            if r.get("suggested_test_name"):
                out.append(f"  - suggested test: "
                           f"`{r['suggested_test_name']}`")
            if r.get("test_in_suite_files"):
                out.append(f"  - in suite: "
                           f"`{', '.join(r['test_in_suite_files'][:3])}`")
        if len(items) > _INLINE_LIMIT:
            out.append(f"- ... +{len(items) - _INLINE_LIMIT} more")
        out.append("")

    out.append("---")
    out.append("*Generated by [`prusik verify-loop check`]("
               "https://github.com/getprusik/prusik).*")
    return "\n".join(out)


def _format_findings(data: dict) -> str:
    """Format `prusik findings --json` output as PR comment."""
    findings = data.get("findings", [])
    out: list[str] = []
    if not findings:
        out.append("## ✅ prusik findings — none")
        out.append("")
        out.append("No actionable findings in the ledger.")
        return "\n".join(out)

    out.append(f"## ⚠ prusik findings — {len(findings)} actionable")
    out.append("")
    for f in findings[:_INLINE_LIMIT]:
        sev = f.get("severity", "?")
        kind = f.get("kind", "?")
        summary = f.get("summary", "?")
        out.append(f"- **[{sev}] {kind}** — {summary}")
        if f.get("suggested_action"):
            out.append(f"  - next: {f['suggested_action']}")
    if len(findings) > _INLINE_LIMIT:
        out.append(f"- ... +{len(findings) - _INLINE_LIMIT} more")
    out.append("")
    out.append("---")
    out.append("*Generated by [`prusik findings`]("
               "https://github.com/getprusik/prusik).*")
    return "\n".join(out)


def _format_prove(data: dict) -> str:
    """Format `prusik prove --json` output as a PR comment."""
    proven = data.get("proven", False)
    cmd = data.get("command", "?")
    reason = data.get("reason", "")
    out: list[str] = []
    if proven:
        out.append("## ✅ prusik prove — PASS")
        out.append("")
        out.append(f"`{cmd}` — {reason}.")
        out.append("")
        out.append("The command **actually ran clean** — verified from its own "
                   "output, not asserted.")
    else:
        out.append("## ❌ prusik prove — NOT PROVEN")
        out.append("")
        out.append(f"`{cmd}`")
        out.append("")
        out.append(f"> {reason}")
        if data.get("exit_code") == 0 and data.get("executed") == 0:
            out.append("")
            out.append("Exit 0 alone does not prove the command ran — this is "
                       "exactly the fabrication this check exists to catch.")
    out.append("")
    out.append("---")
    out.append("*Generated by [`prusik prove`]("
               "https://github.com/getprusik/prusik).*")
    return "\n".join(out)


def format_comment(data: dict) -> str:
    """Auto-detect input shape and dispatch to the right formatter.

    Recognized shapes:
      - prove output:       has "proven" + "command"
      - scan output:        has "detectors" (+ canonical "findings" list)
      - verify-loop output: has "aggregate" with "t0_findings"
      - findings output:    has "schema_version" + "findings" list
      - scan no-files:      has "root" + "stats" (early-return shape, no
                            detectors/total — still a clean scan)
    """
    if "proven" in data and "command" in data:
        return _format_prove(data)
    if "detectors" in data:
        return _format_scan(data)
    if isinstance(data.get("aggregate"), dict) and \
            "t0_findings" in data["aggregate"]:
        return _format_verify_loop(data)
    if "schema_version" in data and "findings" in data:
        return _format_findings(data)
    # scan's "no scannable files" early return: {root, stats, findings: [],
    # message} — no detectors and no schema_version. Route to the scan
    # formatter, which renders the clean message off stats/total.
    if "root" in data and "stats" in data:
        return _format_scan(data)
    # Unknown shape — emit raw as fenced JSON so the comment shows
    # something rather than nothing
    return (f"## prusik ci-comment — unrecognized input\n\n"
            f"```json\n{json.dumps(data, indent=2)[:2000]}\n```")


def run(input_path: str | None = None) -> int:
    """CLI entry. Reads JSON from path or stdin; emits markdown to
    stdout. Returns rc=0 always (the calling Action decides what to
    do with the comment + findings count)."""
    if input_path and input_path != "-":
        try:
            with open(input_path) as f:
                data = json.load(f)
        except (OSError, json.JSONDecodeError) as e:
            print(f"[prusik-ci-comment] cannot read {input_path}: {e}",
                  file=sys.stderr)
            return 2
    else:
        try:
            data = json.load(sys.stdin)
        except json.JSONDecodeError as e:
            print(f"[prusik-ci-comment] invalid JSON on stdin: {e}",
                  file=sys.stderr)
            return 2

    print(format_comment(data))
    return 0
