"""Test-suggestion for binding-mismatch flags — v0.27.0.

Closes the assertion-depth gap STRUCTURALLY, not just by flagging. When
prusik detects a binding mismatch, it KNOWS the bug AND the test that
catches it: the test asserts the consumer URL resolves to the route
(fetch_url class) OR that the handler reads the template's form name
(form_name class).

Today's output: "flagged at line 42; here's the suggested fix."
v0.27.0 output: "flagged at line 42; here's the suggested fix; HERE'S
THE TEST that would have caught this." The operator pastes the test,
fills in the project-specific app import + the value-specific
assertion, and the assertion-depth gap STAYS closed structurally.

Stack-dispatched:
  - Python+FastAPI: pytest + TestClient template
  - JS/TS (Express + Next.js): jest/vitest + supertest template

Honest scope:
  - The suggested test is a SCAFFOLD. Project-specific bits (app import
    location, asserting on RESPONSE BODY rather than just status, etc.)
    require operator/agent completion. Prusik can't know your app's
    import path without reading more of the repo than it conservatively
    does.
  - The fetch_url test is high-value (status-code check is unambiguous).
    The form_name test is lower-value (it can assert "handler runs without
    error when given this key" but can't assert what the handler does
    WITH the value — that's project-specific business logic).
  - Prusik emits suggestions; it does NOT auto-apply them. Same mission
    boundary as the flag itself: prusik mechanizes, operator decides.
"""

from __future__ import annotations

from pathlib import Path


def _stack_of_template(template_path: str) -> str:
    """Heuristic: which stack is this template's binding from?
    Returns 'python' or 'js'."""
    p = Path(template_path).suffix.lower()
    if p in (".html", ".jinja", ".jinja2", ".htm"):
        return "python"
    if p in (".jsx", ".tsx", ".js", ".ts"):
        return "js"
    # Default to python — Jinja templates often have no .html extension
    # (when stored under templates/ without one)
    return "python"


def _safe_name(s: str) -> str:
    """Convert an arbitrary string to a python-identifier-safe slug.
    Guards against:
      - non-alphanumeric chars (replaced with _)
      - leading/trailing underscores (stripped)
      - repeated underscores (collapsed)
      - leading digit (Python identifiers can't start with one;
        prepend `_` to recover)
    """
    out = "".join(c if c.isalnum() else "_" for c in s)
    out = out.strip("_")
    while "__" in out:
        out = out.replace("__", "_")
    if not out:
        return "binding"
    if out[0].isdigit():
        out = "_" + out
    return out


def suggest_test_for_fetch_url(finding: dict) -> dict | None:
    """Emit a test scaffold for a fetch_url binding finding.

    The test asserts: the QUALIFIED route URL (prusik's suggested fix)
    returns non-404 when called as the consumer expects.

    Returns: {"name": <test fn name>, "code": <full code>, "stack": ...}
    or None if the finding doesn't have enough info to scaffold.
    """
    expected = finding.get("expected", [])
    if not expected:
        return None
    target_url = expected[0]
    stack = _stack_of_template(finding.get("template", ""))
    method = finding.get("method", "get").lower()
    test_name = f"test_{_safe_name(target_url)}_is_reachable"

    if stack == "python":
        code = (
            f"def {test_name}():\n"
            f"    \"\"\"Asserts the qualified route URL is reachable.\n"
            f"    Auto-generated by prusik v0.27.0 from a binding-mismatch\n"
            f"    flag. Fill in your app's import below.\"\"\"\n"
            f"    from fastapi.testclient import TestClient\n"
            f"    from <your_module> import app  # TODO: replace with your app import\n"
            f"\n"
            f"    client = TestClient(app)\n"
            f"    response = client.{method}({target_url!r})\n"
            f"    assert response.status_code != 404, (\n"
            f"        f\"Route {target_url} 404'd — the binding-mismatch \"\n"
            f"        f\"flagged by prusik is real. Expected status, got: \"\n"
            f"        f\"{{response.status_code}}\")\n"
        )
    else:  # js
        code = (
            f"// Auto-generated by prusik v0.27.0 from a binding-mismatch flag.\n"
            f"// Fill in your app's import below.\n"
            f"const request = require('supertest');\n"
            f"const app = require('<your_app>');  // TODO: replace with your app import\n"
            f"\n"
            f"test('{target_url} is reachable', async () => {{\n"
            f"  const response = await request(app).{method}('{target_url}');\n"
            f"  expect(response.status).not.toBe(404);\n"
            f"}});\n"
        )

    return {"name": test_name, "code": code, "stack": stack,
            "class": "fetch_url", "target": target_url}


def suggest_test_for_form_name(finding: dict) -> dict | None:
    """Emit a test scaffold for a form_name binding finding.

    The test posts the form with the template's name; the operator
    extends with the assertion of what the handler should DO with the
    value (project-specific business logic).

    Returns: {"name", "code", "stack"} or None if the finding is
    incomplete.
    """
    name = finding.get("name", "")
    if not name:
        return None
    stack = _stack_of_template(finding.get("template", ""))
    test_name = f"test_handler_reads_form_field_{_safe_name(name)}"

    if stack == "python":
        code = (
            f"def {test_name}():\n"
            f"    \"\"\"Asserts the handler reads the template's form field.\n"
            f"    Auto-generated by prusik v0.27.0 from a form_name binding-\n"
            f"    mismatch flag. Fill in app import + assert what the handler\n"
            f"    DOES with the value (prusik can't infer that — project-specific).\"\"\"\n"
            f"    from fastapi.testclient import TestClient\n"
            f"    from <your_module> import app  # TODO: replace with your app import\n"
            f"\n"
            f"    client = TestClient(app)\n"
            f"    response = client.post('<your_form_action_path>',\n"
            f"                            data={{'{name}': 'test-value'}})\n"
            f"    assert response.status_code == 200\n"
            f"    # TODO: assert the handler USED the value — project-specific.\n"
            f"    # Example: assert 'test-value' in response.text\n"
            f"    #          OR assert the DB row got it\n"
        )
    else:
        code = (
            f"// Auto-generated by prusik v0.27.0 from a form_name binding-mismatch flag.\n"
            f"// Fill in app import + assert what the handler DOES with the value.\n"
            f"const request = require('supertest');\n"
            f"const app = require('<your_app>');  // TODO: replace with your app import\n"
            f"\n"
            f"test('handler reads form field {name}', async () => {{\n"
            f"  const response = await request(app)\n"
            f"    .post('<your_form_action_path>')\n"
            f"    .send({{ {name}: 'test-value' }});\n"
            f"  expect(response.status).toBe(200);\n"
            f"  // TODO: assert the handler USED the value — project-specific.\n"
            f"}});\n"
        )

    return {"name": test_name, "code": code, "stack": stack,
            "class": "form_name", "target": name}


def suggest_for_finding(finding: dict) -> dict | None:
    """Dispatch by finding class. Returns None when the finding class
    doesn't have a test-suggestion implementation."""
    cls = finding.get("class") or finding.get("binding_class")
    if cls == "fetch_url":
        return suggest_test_for_fetch_url(finding)
    if cls == "form_name":
        return suggest_test_for_form_name(finding)
    return None
